name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (required for GitHub context)
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ssh_key
          echo "${{secrets.KNOWN_HOSTS}}" &> ~/.ssh/known_hosts
          chmod 600 ssh_key

      - name: SSH and Deploy
        run: |
            echo "${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key"
            ssh -i ~/ssh_key ubuntu@3.88.216.8
            cd monorepoci-cd/ && git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart web-server

